name: Daily Log Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Append today's log
        run: |
          DATE=$(date -u +'%Y-%m-%d')
          echo "- ✅ $DATE: Automated daily log entry" >> README.md

      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "Daily log update: $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
